<?php

if (!defined('ABSPATH'))
    die('Restricted Access');

class MJTC_user
{

    private $MJTC_currentuser = null;
    public $socialmedia = null;

    function __construct()
    {
        if (is_user_logged_in()) { // wp user logged in
            $MJTC_wpuserid = get_current_user_id();
            if (!is_numeric($MJTC_wpuserid))
                return false;
            $MJTC_query = "SELECT * FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE wpuid = " . esc_sql($MJTC_wpuserid);
            $MJTC_currentuser = majesticsupport::$_db->get_row($MJTC_query);
            $majesticsupport_registerform = MJTC_request::MJTC_getVar('ms_support_register_nonce', 'post', '');
            $MJTC_registerform = MJTC_request::MJTC_getVar('majesticsupport_registerform', 'post', 0);
            if ($MJTC_currentuser == '' and ($majesticsupport_registerform == '' && $MJTC_registerform == 0)) {// inserting a record in our table
                $MJTC_userdata = get_userdata($MJTC_wpuserid);
                $MJTC_profile['id'] = '';
                // User display name
                $MJTC_user_first = get_user_meta($MJTC_wpuserid, 'first_name', true);
                $MJTC_user_last = get_user_meta($MJTC_wpuserid, 'last_name', true);
                if ($MJTC_user_first && $MJTC_user_last) {
					$MJTC_display_name = $MJTC_user_first . ' ' . $MJTC_user_last;
                } elseif ($MJTC_user_first) {
                    $MJTC_display_name = $MJTC_user_first;
                } elseif ($MJTC_user_last) {
                    $MJTC_display_name = $MJTC_user_last;
                } else {
                    $MJTC_display_name = $MJTC_userdata->display_name;
                }

                $MJTC_profile['name'] = $MJTC_display_name;
                if ($MJTC_userdata->display_name == '') {
                    $MJTC_profile['name'] = $MJTC_userdata->user_nicename;
                }
                $MJTC_profile['email'] = $MJTC_userdata->user_email;
                $MJTC_profile['wpuid'] = $MJTC_wpuserid;
                $MJTC_profile['created'] = date_i18n('Y-m-d H:i:s');
                $MJTC_profile['status'] = 1;
                $MJTC_profile['autogenerated'] = 1;

                $MJTC_row = MJTC_includer::MJTC_getTable('users');
                $MJTC_data['id'] = '';
                $MJTC_data['wpuid'] = $MJTC_wpuserid;
                $MJTC_data['name'] = $MJTC_profile['name'];
                $MJTC_data['display_name'] = $MJTC_display_name;
                $MJTC_data['user_nicename'] = $MJTC_userdata->user_nicename;
                $MJTC_data['user_email'] = $MJTC_userdata->user_email;
                $MJTC_data['issocial'] = 0;
                $MJTC_data['socialid'] = null;
				$MJTC_data['created'] = date_i18n('Y-m-d H:i:s');
                $MJTC_data['status'] = 1;
                $MJTC_data['autogenerated'] = 1;
                $MJTC_row->bind($MJTC_data);
                $MJTC_row->store();

                if (is_numeric($MJTC_row->id)) {
                    $MJTC_query = "SELECT * FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE id = " . esc_sql($MJTC_row->id);
                    $MJTC_currentuser = majesticsupport::$_db->get_results($MJTC_query);
                }
            }
            $this->MJTC_currentuser = $MJTC_currentuser;
        } else { // wp user is not logged in
            if (in_array('sociallogin', majesticsupport::$_active_addons)){
                if (isset($_COOKIE['majesticsupport-socialid']) && !empty($_COOKIE['majesticsupport-socialid'])) { // social user is logged in
                    $MJTC_query = "SELECT * FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE socialid = '" . esc_sql(majesticsupport::MJTC_sanitizeData($_COOKIE['majesticsupport-socialid'])) . "'";// MJTC_sanitizeData() function uses wordpress santize functions
                    $this->MJTC_currentuser = majesticsupport::$_db->get_row($MJTC_query);

                    $this->socialmedia = isset($_COOKIE['majesticsupport-socialmedia']) ? majesticsupport::MJTC_sanitizeData($_COOKIE['majesticsupport-socialmedia']) : '';// MJTC_sanitizeData() function uses wordpress santize functions
                }
            }
        }
    }

    function MJTC_isguest()
    {
        if (isset($_COOKIE['majesticsupport-socialid']) && !empty($_COOKIE['majesticsupport-socialid'])) {
            if (in_array('sociallogin', majesticsupport::$_active_addons)) {
                return false;
            } else {
                return true;
            }
        } elseif ($this->MJTC_currentuser == null && !is_user_logged_in()) { // current user is guest
            return true;
        } else {
            return false;
        }
    }

    function MJTC_isdisabled()
    {
        if ($this->MJTC_currentuser != null && $this->MJTC_currentuser->status == 0) { // current user is disabled
            return true;
        } else {
            return false;
        }
    }

    function MJTC_uid()
    {

        if ($this->MJTC_currentuser != null) {

            return $this->MJTC_currentuser->id;
        }
    }

    function MJTC_wpuid()
    {

        if ($this->MJTC_currentuser != null) {

            return $this->MJTC_currentuser->wpuid;
        }
    }

    function MJTC_emailaddress()
    {
        if ($this->MJTC_currentuser == null) { // current user is guest
            return false;
        } else {
            return $this->MJTC_currentuser->user_email;
        }
    }

    function MJTC_fullname()
    {
        if ($this->MJTC_currentuser == null) { // current user is guest
            return false;
        } else {
            $MJTC_name = $this->MJTC_currentuser->name;
            if($MJTC_name == ""){
                $MJTC_name = $this->MJTC_currentuser->display_name;
            }
            if($MJTC_name == ""){
                $MJTC_name = $this->MJTC_currentuser->user_nicename;
            }
            if($MJTC_name == ""){ // get from wordpress
                $MJTC_current_user = wp_get_current_user();
                if(0 != $MJTC_current_user->ID){
                    $MJTC_name = $MJTC_current_user->user_firstname.' '.$MJTC_current_user->user_lastname;
                    if($MJTC_name == ""){
                        $MJTC_name = $MJTC_current_user->display_name;
                    }
                }
            }
            return $MJTC_name;
        }
    }


    function MJTC_isMajesticSupportUser()
    {
        if (is_user_logged_in()) { // wp user logged in
            $MJTC_wpuserid = MJTC_includer::MJTC_getObjectClass('user')->MJTC_uid();
            if (!is_numeric($MJTC_wpuserid))
                return false;
            $MJTC_query = "SELECT COUNT(id) FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE wpuid = " . esc_sql($MJTC_wpuserid);
            $MJTC_result = majesticsupport::$_db->get_results($MJTC_query);
            if ($MJTC_result > 0) {
                return true;
            } else {
                return false;
            }
        } else {
            if (isset($_COOKIE['majesticsupport-socialid']) && !empty($_COOKIE['majesticsupport-socialid'])) { // social user is logged in
                $MJTC_query = "SELECT COUNT(id) FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE socialid = '" . esc_sql(majesticsupport::MJTC_sanitizeData($_COOKIE['majesticsupport-socialid'])) . "'";// MJTC_sanitizeData() function uses wordpress santize functions
                $MJTC_result = majesticsupport::$_db->get_results($MJTC_query);
                if ($MJTC_result > 0) {
                    return true;
                } else {
                    return false;
                }
            }
        }
    }

    function MJTC_isSocialLogin()
    {
        if (isset($_COOKIE['majesticsupport-socialid']) && !empty($_COOKIE['majesticsupport-socialid'])) {
            return true;
        } else {
            return false;
        }
    }

    function MJTC_getmajesticsupportuidbyuserid($MJTC_userid)
    {
        if (!is_numeric($MJTC_userid)) return false;
        $MJTC_query = "SELECT id FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE wpuid = " . esc_sql($MJTC_userid);
        $MJTC_uid = majesticsupport::$_db->get_results($MJTC_query);
        return $MJTC_uid;
    }

    function MJTC_getMSCurrentUser(){
        return $this->MJTC_currentuser;
    }

    function MJTC_deleteUserRecords($MJTC_uid , $MJTC_is_delete_user = false ){
        if(! is_numeric($MJTC_uid))
            return false;
        $model = MJTC_includer::MJTC_getModel('ticket');
        $MJTC_query = "SELECT id , ticketid FROM `".majesticsupport::$_db->prefix."mjtc_support_tickets` WHERE wpuid = ".esc_sql($MJTC_uid);
        $MJTC_tickets = majesticsupport::$_db->get_results($MJTC_query);

        do_action('MJTC_addon_deletequery_for_user');
        $MJTC_query = "DELETE  ticket, reply,attachment,activity_log,erasedatarequests ". majesticsupport::$_addon_query['select'] . "
            FROM `". majesticsupport::$_db->prefix ."mjtc_support_users` AS user
            LEFT JOIN `". majesticsupport::$_db->prefix ."mjtc_support_tickets` AS ticket ON ticket.uid = user.id
            LEFT JOIN `". majesticsupport::$_db->prefix ."mjtc_support_replies` AS reply ON reply.ticketid = ticket.id
            LEFT JOIN `". majesticsupport::$_db->prefix ."mjtc_support_attachments` AS attachment ON attachment.ticketid = ticket.id
            LEFT JOIN `". majesticsupport::$_db->prefix ."mjtc_support_activity_log` AS activity_log ON activity_log.uid = user.id
            LEFT JOIN `". majesticsupport::$_db->prefix ."mjtc_support_erasedatarequests` AS erasedatarequests ON erasedatarequests.uid = user.id
            "
            . majesticsupport::$_addon_query['join'] . "
            WHERE user.id = " . esc_sql($MJTC_uid);
        majesticsupport::$_db->query($MJTC_query);
        do_action('MJTC_reset_addon_query');
        $MJTC_query = "DELETE user FROM `".majesticsupport::$_db->prefix."mjtc_support_users` AS user WHERE wpuid = " . esc_sql($MJTC_uid);
        if(majesticsupport::$_db->query($MJTC_query)){
            // --- START FILESYSTEM FIX ---
            global $wp_filesystem;
            if (!function_exists('wp_handle_upload')) {
                do_action('majesticsupport_load_wp_file');
            }
            if ( ! WP_Filesystem() ) {
                return false;
            }
            $MJTC_wp_filesystem = $wp_filesystem;

            $MJTC_maindir = wp_upload_dir();
            $MJTC_basedir = $MJTC_maindir['basedir'];
            $MJTC_datadirectory = majesticsupport::$_config['data_directory'];
            $MJTC_path = $MJTC_basedir . '/' . $MJTC_datadirectory. '/attachmentdata/ticket';
            foreach ($MJTC_tickets as $MJTC_key) {
                $MJTC_userpath = $MJTC_path . '/' . $MJTC_key->ticketid;

                // Replaced glob, is_file, and rmdir with WP_Filesystem delete
                if ($MJTC_wp_filesystem->exists($MJTC_userpath)) {
                    $MJTC_wp_filesystem->delete($MJTC_userpath, true); // true means recursive (deletes files inside too)
                }
            }
            return true;
        }else{
            return false;
        }
    }

    function MJTC_getUserIDByWPUid($MJTC_wpuid) {
        if (!is_numeric($MJTC_wpuid))
            return false;

        $MJTC_query = "SELECT id FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE wpuid = " . esc_sql($MJTC_wpuid);
        $MJTC_result = majesticsupport::$_db->get_var($MJTC_query);
        return $MJTC_result;
    }

    function MJTC_getUserNameByUid($MJTC_uid) {
        if (!is_numeric($MJTC_uid))
            return false;

        $MJTC_query = "SELECT display_name,user_nicename FROM `".majesticsupport::$_db->prefix."mjtc_support_users` WHERE id = " . esc_sql($MJTC_uid);
        $MJTC_result = majesticsupport::$_db->get_row($MJTC_query);
        return $MJTC_result;
    }

}

