<?php

if (!defined('ABSPATH'))
    die('Restricted Access');

if (!defined('MJTC_ALLOWED_TAGS')) {
    define('MJTC_ALLOWED_TAGS', array(
        'div'      => array(
            'class'  => array(),
            'id' => array(),
            'data-sitekey' => array(),
            'title' => array(),
            'role' => array(),
            'onclick' => array(),
            'onmouseout' => array(),
            'onmouseover' => array(),
            'data-section' => array(),
            'data-sectionid' => array(),
            'data-sitekey' => array(),
            'data-boxid' => array(),
            'data-per' => array(),
            'data-nonce' => array(),
            'style' => array(),
        ),
        'button'      => array(
            'class'  => array(),
            'id' => array(),
            'type' => array(),
            'title' => array(),
            'role' => array(),
            'data-dismiss' => array(),
            'aria-label' => array(),
            'style' => array(),
        ),
        'i'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h1'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h2'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h3'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h4'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h5'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'h6'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),  
        ),
        'font'      => array(
            'class'  => array(),
            'id' => array(),
            'style' => array(),
        ),
        'span'      => array(
            'class'  => array(),
            'id' => array(),
            'aria-hidden' => array(),
            'style' => array(),
            'data-tooltip' => array(),
        ),
        'input'      => array(
            'type'  => array(),
            'id' => array(),
            'class' => array(),
            'name' => array(),
            'value' => array(),
            'onclick' => array(),
            'data-validation' => array(),
            'required' => array(),
            'size' => array(),
            'placeholder' => array(),
            'checked' => array(),
            'autocomplete' => array(),
            'multiple' => array(),
            'rel' => array(),
            'maxlength' => array(),
            'disabled' => array(),
            'readonly' => array(),
            'credit_userid' => array(),
            'data-dismiss' => array(),
            'data-validation-optional' => array(),
            'data-callback' => array(),
            'data-action' => array(),
            'data-sitekey' => array(),
            'style' => array(),
            'onchange' => array(),
            'tabindex' => array(),
        ),
        'textarea'     => array(
            'rows' => array(),
            'name' => array(),
            'class' => array(),
            'id' => array(),
            'value' => array(),
            'cols' => array(),
            'data-validation' => array(),
            'autocomplete' => array(),
            'style' => array(),
            'disabled' => array(),
            'readonly' => array(),
            'placeholder' => array(),
        ),
        'button'      => array(
            'type'  => array(),
            'id' => array(),
            'class' => array(),
            'name' => array(),
            'value' => array(),
            'onclick' => array(),
            'data-validation' => array(),
            'required' => array(),
            'data-dismiss' => array(),
            'style' => array(),
        ),
        'select'      => array(
            'id' => array(),
            'class' => array(),
            'name' => array(),
            'onchange' => array(),
            'data-validation' => array(),
            'required' => array(),
            'multiple' => array(),
            'data-nonce' => array(),
            'style' => array(),
            'disabled' => array(),
            'readonly' => array(),
            'tabindex' => array(),
        ),
        'option'      => array(
            'id' => array(),
            'class' => array(),
            'name' => array(),
            'value' => array(),
            'selected' => array(),
            'style' => array(),
        ),
        'img'      => array(
            'src'  => array(),
            'id' => array(),
            'class' => array(),
            'onclick' => array(),
            'alt' => array(),
            'width' => array(),
            'height' => array(),
            'border' => array(),
            'style' => array(),
        ),
        'link'      => array(
            'src'  => array(),
            'id' => array(),
            'rel' => array(),
            'href' => array(),
            'media' => array(),
            'style' => array(),
        ),
        'meta'      => array(
            'property'  => array(),
            'content' => array(),
            'style' => array(),
        ),
        'a'      => array(
            'href'  => array(),
            'title' => array(),
            'onclick' => array(),
            'id' => array(),
            'class' => array(),
            'name' => array(),
            'data-toggle' => array(),
            'data-id' => array(),
            'data-name' => array(),
            'data-email' => array(),
            'data-ticketid' => array(),
            'data-username' => array(),
            'message' => array(),
            'confirmmessage' => array(),
            'data-for' => array(),
            'data-sortby' => array(),
            'data-image1' => array(),
            'data-image2' => array(),
            'data-gall' => array(),
            'data-vbtype' => array(),
            'target' => array(),
            'data-tab-number' => array(),
            'data-gall' => array(),
            'data-vbtype' => array(),
            'style' => array(),
        ),
        'ul'      => array(
            'type'  => array(),
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'ol'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'li'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'dl'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'dt'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'dd'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'table'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'tr'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'td'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'th'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'p'      => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'form'      => array(
            'id' => array(),
            'class' => array(),
            'method' => array(),
            'action' => array(),
            'enctype' => array(),
        ),
        'label'      => array(
            'id' => array(),
            'class' => array(),
            'for' => array(),
            'onclick' => array(),
            'style' => array(),
        ),
        'i'     => array(
            'id' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'script'     => array(
            'type' => array(),
            'class' => array(),
            'style' => array(),
        ),
        'br'     => array(
            'style' => array(),),
        'hr'     => array(
            'style' => array(),),
        'b'     => array(
            'style' => array(),),
        'em'     => array(
            'style' => array(),),
        'strong' => array(
            'style' => array(),
        ),
        'small' => array(
            'style' => array(),),
        '&nbsp' => array(),
        'svg' => array(
            'class'           => array(),
            'xmlns'           => array(),
            'xmlns:xlink'     => array(),
            'version'         => array(),
            'x'               => array(),
            'y'               => array(),
            'viewbox'         => array(), // lowercase
            'width'           => array(),
            'height'          => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
            'stroke-linecap'  => array(),
            'stroke-linejoin' => array(),
            'aria-hidden'     => array(),
            'focusable'       => array(),
            'role'            => array(),
            'style'           => array(),
        ),
        'g' => array(
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
            'stroke-linecap'  => array(),
            'stroke-linejoin' => array(),
            'class'           => array(),
            'transform'       => array(),
        ),
        'path' => array(
            'd'               => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
            'stroke-linecap'  => array(),
            'stroke-linejoin' => array(),
            'class'           => array(),
        ),
        'circle' => array(
            'cx'              => array(),
            'cy'              => array(),
            'r'               => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'ellipse' => array(
            'cx'              => array(),
            'cy'              => array(),
            'rx'              => array(),
            'ry'              => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'rect' => array(
            'x'               => array(),
            'y'               => array(),
            'width'           => array(),
            'height'          => array(),
            'rx'              => array(), // rounded corners
            'ry'              => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'line' => array(
            'x1'              => array(),
            'y1'              => array(),
            'x2'              => array(),
            'y2'              => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'polyline' => array(
            'points'          => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'polygon' => array(
            'points'          => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'text' => array(
            'x'               => array(),
            'y'               => array(),
            'dx'              => array(),
            'dy'              => array(),
            'text-anchor'     => array(),
            'font-family'     => array(),
            'font-size'       => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
        'tspan' => array(
            'x'               => array(),
            'y'               => array(),
            'dx'              => array(),
            'dy'              => array(),
            'text-anchor'     => array(),
            'fill'            => array(),
            'stroke'          => array(),
            'stroke-width'    => array(),
        ),
    ));
    define(
        'MJTC_DEFAULT_LANGUAGES',
            array(
                'ar',
                'de_DE',
                'es_ES',
                'fr_FR',
                'it_IT',
                'pt_BR',
            )
    );
}
define('MJTC_PLUGIN_PATH', plugin_dir_path( __DIR__ ));
define('MJTC_PLUGIN_URL', plugin_dir_url( __DIR__ ));
?>
